In [1]:
import pandas as pd
from pandas_datareader import data

def load_financial_data(symbol,start_date,end_date,output_file):
  try:
    df = pd.read_pickle(output_file)
    print('File Exist . . Reading Data')
  except:
    print(f'File Not Found . . downloading {symbol} data')
    df = data.DataReader(symbol,'yahoo',start_date,end_date)
    df.to_pickle(f'{output_file}')
  return df
  
goog_data = load_financial_data('GOOG','2020-04-30','2022-04-30','GOOG_data.pkl')

File Not Found . . downloading GOOG data

In [2]:
goog_data

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2668900,1348.660034
2020-05-01,1352.069946,1311.000000,1328.500000,1320.609985,2072500,1320.609985
2020-05-04,1327.660034,1299.000000,1308.229980,1326.800049,1504000,1326.800049
2020-05-05,1373.939941,1337.459961,1337.920044,1351.109985,1651500,1351.109985
2020-05-06,1371.119995,1347.290039,1361.689941,1347.300049,1215400,1347.300049
...,...,...,...,...,...,...
2022-04-25,2465.560059,2375.385010,2388.590088,2465.000000,1726100,2465.000000
2022-04-26,2455.000000,2383.237061,2455.000000,2390.120117,2469700,2390.120117
2022-04-27,2350.000000,2262.485107,2287.459961,2300.409912,3111900,2300.409912
2022-04-28,2408.770020,2302.877930,2342.300049,2388.229980,1839500,2388.229980
2022-04-29,2379.199951,2293.879883,2351.560059,2299.330078,1683500,2299.330078